CC=gcc

TARGET=hello.c

all: $(TARGET)

$(TARGET): $(TARGET).o
	$(CC) $(TARGET).o -o $(TARGET)

$(TARGET).o: $(TARGET).c
	$(CC) -c $(TARGET).c

clean:
	rm -f $(TARGET) $(TARGET).o

run: $(TARGET)
	./$(TARGET)
